name: models
description: Shared data models for apps
publish_to: "none"
resolution: workspace
version: 1.0.0

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter
  freezed_annotation: ^3.0.0
  json_annotation: ^4.9.0
dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.5.0
  json_serializable: ^6.9.5
  freezed: ^3.0.6

flutter:
  uses-material-design: true
