name: repo
description: Shared repository for apps.
publish_to: "none"
resolution: workspace
version: 1.0.0

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter
  core:
    path: ../core
  models:
    path: ../models
  flutter_riverpod: ^2.6.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner: ^2.5.1
  riverpod_generator: ^2.6.5

flutter:
  uses-material-design: true
