name: auth
description: Shared auth for apps.
publish_to: "none"
resolution: workspace
version: 1.0.0

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter
  core:
    path: ../core
  system_assets:
    path: ../system_assets
  models:
    path: ../models
  repo:
    path: ../repo
  common:
    path: ../common
  crypto: ^3.0.6
  flutter_hooks: ^0.21.2
  riverpod_annotation: ^2.6.1
  freezed_annotation: ^3.0.0
  hooks_riverpod: ^2.6.1
  go_router: ^16.0.0
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  freezed: ^3.0.6
  build_runner: ^2.5.3
  riverpod_generator: ^2.6.5
  json_serializable: ^6.9.5

flutter:
  uses-material-design: true
