name: common
description: Shared widgets and pages for apps.
publish_to: "none"
resolution: workspace
version: 1.0.0

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter
  core:
    path: ../core
  system_assets:
    path: ../system_assets
  models:
    path: ../models
  repo:
    path: ../repo
  flutter_hooks: ^0.21.2
  go_router: ^16.0.0
  hooks_riverpod: ^2.6.1
  url_launcher: ^6.3.2
  flutter_riverpod: ^2.6.1
  freezed_annotation: ^3.1.0
  riverpod_annotation: ^2.6.1
  geocoding: ^4.0.0
  geolocator: ^14.0.2
  table_calendar: ^3.2.0
  pdf: ^3.11.3
  open_filex: ^4.7.0
  path_provider: ^2.1.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner: ^2.5.1
  riverpod_generator: ^2.6.5

flutter:
  uses-material-design: true
