name: core
description: Shared core utilities for apps.
publish_to: "none"
resolution: workspace
version: 1.0.0

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter
  system_assets:
    path: ../system_assets
  models:
    path: ../models
  cupertino_icons: ^1.0.8
  dartz: ^0.10.1
  logger: ^2.5.0
  intl: ^0.20.2
  freezed_annotation: ^3.0.0
  injectable: ^2.5.0
  connectivity_plus: ^6.1.4
  flutter_spinkit: ^5.2.1
  package_info_plus: ^8.3.0
  flutter_svg: ^2.1.0
  file_picker: ^10.2.0
  image_picker: ^1.1.2
  google_fonts: ^6.2.1
  firebase_auth: ^5.6.0
  cloud_firestore: ^5.6.9
  firebase_storage: ^12.4.7
  flutter_riverpod: ^2.6.1
  riverpod_annotation: ^2.6.1
  hooks_riverpod: ^2.6.1
  pinput: ^5.0.1
  json_annotation: ^4.9.0
  go_router: ^16.0.0
  url_launcher: ^6.3.1
  google_mlkit_face_detection: ^0.13.1
  external_app_launcher: ^4.0.3
  device_info_plus: ^11.5.0
  flutter_dotenv: ^6.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.15
  json_serializable: ^6.9.5
  riverpod_generator: ^2.6.5
  injectable_generator: ^2.7.0
  freezed: ^3.0.6

flutter:
  uses-material-design: true
